title: Paul # 页面上展示的标题
SEOTitle: Paul | Docs # 标签展示的标题
header-img: img/post-bg-desk.jpg # 页面顶部图片
email: 13621905107@163.com # 邮箱地址
description: "Daily docs." # 顶部子标题
keyword: "iOS, Apple, iPhone" # 关键字
url: "https://paulpaulbobo.github.io/docs/"          # 网站首页地址
baseurl: "https://paulpaulbobo.github.io/docs/"      # 网站首页地址
github_repo: "https://github.com/PaulPaulBoBo/docs.git" # 网站代码github地址

# 右侧边栏设置
sidebar: true # 是否展示侧边栏
sidebar-about-description: "Paul" # 头像下方的描述
sidebar-avatar: /img/about-BY-gentle.jpg      # 头像地址

# 社交网络设置
RSS: true #是否展示RSS(聚合内容)
github_username: PaulPaulBoBo # github用户名
jianshu_username: 327fb570a3e8 # 简书用户ID

# Jekyll 构建设置
# date /:categories/:year/:month/:day/:title:output_ext
# pretty /:categories/:year/:month/:day/:title/
# ordinal /:categories/:year/:y_day/:title:output_ext
# weekdate /:categories/:year/W:week/:short_day/:title:output_ext
# none /:categories/:title:output_ext
permalink: pretty # 设置构造的文件名格式
paginate: 10 # 设置单页展示的文章数
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"] # 排除的目录或文件
anchorjs: true

# Gems
gems: [jekyll-paginate]

# Markdown 设置
# kramdown文档: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
# gitalk:
#   enable: false    #是否开启Gitalk评论
  # clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  # clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  # repo: qiubaiying.github.io    #仓库名称
  # owner: qiubaiying    #github用户名
  # admin: qiubaiying
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# 首页 Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 1 # 相同标签数量大于这个数，才会出现在首页

# 手机端web配置
chrome-tab-theme-color: "#f5f5f5" # 主题颜色
service-worker: true



# 网站链接
friends: [
    {
        title: "Paul",
        href: "https://paulpaulbobo.github.io/docs/"
    },{
        title: "简书·Paul",
        href: "http://www.jianshu.com/u/327fb570a3e8"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]

theme: jekyll-theme-cayman
