title: Paul # 页面上展示的标题
SEOTitle: Paul | Docs # 标签展示的标题
header-img: img/post-bg-debug.jpg # 页面顶部图片
email: 13621905107@163.com # 邮箱地址
description: "Daily docs." # 顶部子标题
keyword: "iOS, Apple, iPhone" # 关键字
url: "https://paulpaulbobo.github.io/docs"          # 网站首页地址
baseurl: "https://paulpaulbobo.github.io/docs"      # 网站首页地址
github_repo: "https://github.com/PaulPaulBoBo/docs.git" # 网站代码github地址

# 右侧边栏设置
sidebar: true # 是否展示侧边栏
sidebar-about-description: "Paul" # 头像下方的描述

# 社交网络设置
RSS: true #是否展示RSS(聚合内容)
github_username: PaulPaulBoBo # github用户名
jianshu_username: 327fb570a3e8 # 简书用户ID
bokeyuan_username: PaulpauL #博客园用户名

# Jekyll 构建设置
# date /:categories/:year/:month/:day/:title:output_ext
# pretty /:categories/:year/:month/:day/:title/
# ordinal /:categories/:year/:y_day/:title:output_ext
# weekdate /:categories/:year/W:week/:short_day/:title:output_ext
# none /:categories/:title:output_ext
permalink: pretty # 设置构造的文件名格式
paginate: 20 # 设置单页展示的文章数
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"] # 排除的目录或文件
anchorjs: true

# Gems
gems: [jekyll-paginate]

# Markdown 设置
# kramdown文档: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# 首页 Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 2 # 相同标签数量大于这个数，才会出现在首页

# 手机端web配置
chrome-tab-theme-color: "#f5f5f5" # 主题颜色
service-worker: true



# 网站链接
friends: []

theme: jekyll-theme-cayman
